# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Amazon ECS Task Definition Jinja2 based renderer
        uses: lejmr/amazon-ecs-render-task-definition@v1
        with:
          # The path to the ECS task definition JSON file
          task-definition: simple-task-definition.json
          # Path to the file or directory holding values interpolating the task definition. Multiple space separated paths are possible.
          values: values/DEV.json

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cat task-definition-rendered.json
